[server]
runOnSave = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00fff2"
backgroundColor = "#050508"
secondaryBackgroundColor = "#0a0a0f"
textColor = "#e2e8f0"
